# array_job.sub
universe    = vanilla
executable  = /star/u/fliu5/Blume-Capel-Model-/run.sh
arguments   = $(Process)

output      = output/job.$(Cluster)_$(Process).out
error       = error/job.$(Cluster)_$(Process).err
log         = log/job.$(Cluster)_$(Process).log

request_cpus   = 1
request_memory = 4GB
request_disk   = 2GB

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /star/u/fliu5/Blume-Capel-Model-/
queue 221
           
